[Metadata]
 Name                             = SimpleCred
 Version                          = 1.0.0
 Author                           = deflore08 (deflore08@gmail.com) | https://www.deviantart.com/deflore08
 License                          = Creative Commons Attribution-Non-Commercial-Share Alike 4.0
 Information                      = Little tool for easy access to most usable credentials

[Variables]

; --- Var to open this fucking file

 Set_Cred                         = #@#config\creds.inc

; --- CREDENTIALS

 Login_1                          = Login_1
 Password_1                       = Password_1


 Login_2                          = Login_2
 Password_2                       = Password_2

 Login_3                          = Login_3
 Password_3                       = Password_3