[Metadata]
 Name                             = SimpleCred
 Version                          = 1.0.0
 Author                           = deflore08 (deflore08@gmail.com) | https://www.deviantart.com/deflore08
 License                          = Creative Commons Attribution-Non-Commercial-Share Alike 4.0
 Information                      = Little tool for easy access to most usable credentials

[style.Font_Main]
 FontColor                        = #Font_Main_Color#
 FontFace                         = #Font_Main_Face#
 FontSize                         = #Font_Main_Size#
 AntiAlias                        = 1

[style.Font_Secondary]